name: Deploy iOS SDK
on:
  push:
    branches: [ master, ap/chatx-863-auto-deployment]
jobs:
  build:
    name: Build & Deploy
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"